#!/bin/sh

# A dwmblocks function to show the current network connection/SSID, private IP, and public IP using NetworkManager
# GNU GPLv3

# Dependencies: NetworkManager, curl

# Get network information
CONNAME=$(nmcli -a | grep 'Wired connection' | awk 'NR==1{print $1}' | tr ':' ' ')
if [ "$CONNAME" = "" ]; then
    CONNAME=$(nmcli -t -f active,ssid dev wifi | grep '^yes' | cut -c 5-)
fi

PRIVATE=$(nmcli -a | grep 'inet4 192' | awk '{print $2}')
PUBLIC=$(curl -s https://ipinfo.io/ip)

# Determine output format based on identifier (if needed)
if [ "$1" = "" ]; then
    printf " %svia %s" "$CONNAME" "$PRIVATE"
else
    printf " %svia %s" "$CONNAME" "$PRIVATE"
fi
